### ISSUE TITLE
404 error 

### ISSUE THREAD

**Issue by benoitvb** [thomasaull/RestApiProfile#4]
Hi,
Thanks for this great site profile !

After building my project I'm having a 404 error when trying to reach a page from its url.
It works with the /login though but I guess this is because this page doesn't exist as a page with processwire. 

Could you help me with this please ?

**Comment by thomasaull** [comment]
Please see: https://processwire.com/talk/topic/17926-rest-api-site-profile/?do=findComment&comment=168297
